name: plasmabio-template-UEG27
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - jupyterlab=2
  - nbresuse
  - python>=3.7
  - r-base>=4.0
  - pip
  - nodejs
  - bbmap
  - pip:
    - bash_kernel
